### ISSUE TITLE
Value cannot be null, parameter name: input

### ISSUE THREAD

**Issue by gingerbeardman** [daPhie79/hakchi2#1]
![screen shot 2018-01-18 at 00 09 14](https://user-images.githubusercontent.com/49612/35074337-4c2d02aa-fbe5-11e7-8c9e-7005b7124ce0.png)

**Comment by daPhie79** [comment]
oh dear, i'll need more context than that to even try to help!
- did you get this message running the debug build?
- were you adding the game? or uploading?
etc.

**Comment by gingerbeardman** [comment]
Hi, I was dragging adding a zipped rom onto the non-debug version. Also happens with any unzipped rom.

Interestingly the debug version works fine!

**Comment by daPhie79** [comment]
yes, it bypasses more bugs though it's not a wanted effect it's how it's been built mostly, lol, but i'm fairly sure i've found what was the problem. when i release my next build, it will surely work better!

**Comment by gingerbeardman** [comment]
I'll be sure to check.

**Comment by gingerbeardman** [comment]
Can I test the 7a68000 changes?

**Comment by daPhie79** [comment]
of course you can try my last build it should fix this!
________________________________

**Comment by gingerbeardman** [comment]
fixed in latest debug builds
