### ISSUE TITLE
HDMI full color range

### ISSUE THREAD

**Issue by mzino** [daPhie79/hakchi2#3]
Since you're actively improving hakchi2, I'm bringing attention to an enhancement that was requested months ago on the original repo. 

https://github.com/ClusterM/hakchi2/issues/724

For those of us that use a monitor, this would be a great addition. I'm trying to recompile the [kernel](https://github.com/madmonkey1907/sun-nontendocm-kernel) myself but I'm struggling due to lack of experience, and maybe someone knows right away where to look - and if this feature is even feasible in the first place.

**Comment by daPhie79** [comment]
oh i'd love to help, but my knowledge really is about the windows interface and programming, so i can't help for the actual snesc hack, sorry! thank you for your interest in my fork though :)
